from pydantic import BaseModel
from typing import Optional

class EmployeeRead(BaseModel):
    Workday_ID: int
    Employee_Name: Optional[int]            # matches DB integer
    EMAIL: Optional[int]                    # matches DB integer
    Status: Optional[str]
    Business_Title: Optional[str]
    Practices: Optional[str]
    Services_L2: Optional[str]
    Services_L3: Optional[str]
    Services_L4: Optional[str]
    Job_Family_Group: Optional[str]
    JOB_FAMILY: Optional[str]
    Job_Profile_Name: Optional[str]
    DCF_LEVELS: Optional[int]
    Workday_Cost_Centre: Optional[str]
    Workday_Profit_Centre: Optional[str]
    Business_Category: Optional[str]
    Delivery_Centre: Optional[str]
    Skills: Optional[str]
    Certifications: Optional[str]
    DGS_Office_Location: Optional[str]
    Reporting_Manager_ID: Optional[int]
    Reporting_Manager_Name: Optional[int]   # matches DB integer
    Service_Line_Lead: Optional[str]
    Practice_Lead: Optional[str]
    Sub_Practice_Lead: Optional[str]
    Sub_Sub_Practice_Lead: Optional[str]
    DB_Type: Optional[str]
    Resource_Category: Optional[str]
    DGS_Practice_FTE_Sub_Classification: Optional[str]
    Column_30: Optional[int]
    fixed_col_1: Optional[int]
    fixed_col_2: Optional[int]
    fixed_col_3: Optional[int]
    fixed_col_4: Optional[str]
    fixed_col_5: Optional[str]
    fixed_col_6: Optional[str]
    fixed_col_7: Optional[str]
    fixed_col_8: Optional[str]
    fixed_col_9: Optional[str]
    fixed_col_10: Optional[str]
    fixed_col_11: Optional[str]
    fixed_col_12: Optional[str]
    fixed_col_13: Optional[int]
    fixed_col_14: Optional[str]
    fixed_col_15: Optional[int]
    fixed_col_16: Optional[int]
    fixed_col_17: Optional[int]
    fixed_col_18: Optional[str]
    fixed_col_19: Optional[str]
    fixed_col_20: Optional[str]
    fixed_col_21: Optional[str]
    fixed_col_22: Optional[str]
    fixed_col_23: Optional[str]
    fixed_col_24: Optional[str]
    fixed_col_25: Optional[str]
    fixed_col_26: Optional[str]
    fixed_col_27: Optional[int]
    fixed_col_28: Optional[str]
    fixed_col_29: Optional[str]
    fixed_col_30: Optional[str]
    fixed_col_31: Optional[str]
    fixed_col_32: Optional[str]
    fixed_col_33: Optional[str]
    fixed_col_34: Optional[str]
    fixed_col_35: Optional[int]
    fixed_col_36: Optional[int]
    fixed_col_37: Optional[str]
    fixed_col_38: Optional[str]

    class Config:
        orm_mode = True
